# Generated by Django 6.1 on 2026-09-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('profile_photo', models.ImageField(blank=True, upload_to='doctors/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('specialization', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=80)),
                ('qualification', models.CharField(max_length=150)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.CharField(max_length=120)),
                ('available_time', models.CharField(max_length=80)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('On Leave', 'On Leave')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
