# Generated by Django 6.1 on 2026-09-17 07:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='billing',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='patients.department'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Insurance', 'Insurance')], default='Cash', max_length=20),
        ),
    ]
