# Generated by Django 6.1 on 2026-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_hospitalsettings_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
